[package]
name = "dfs_usage_audit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.37"
jwalk = "0.8.1"
rayon = "1.10.0"
walkdir = "2.5.0"
